# Generated by Django 3.2.9 on 2021-12-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='metro_population',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='metro_population'),
        ),
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='city_photos'),
        ),
    ]
